### ISSUE TITLE
Update to CE 2020

### ISSUE THREAD

**Issue by senier** [Componolit/gneiss#178] opened 2020-05-25 13:12 UTC

**Comment by jklmnn** [comment] 2020-05-25 17:38
This needs https://github.com/Componolit/SXML/issues/81.

**Comment by jklmnn** [comment] 2020-05-28 16:24
The proofs for the global state of a component are mutually exclusive. `Component.Main.Platform` needs to be in the initialized states in `Component` for GNAT CE 2020. For GNAT CE 2019 it must not be inside the initialized states. I assume we want to make GNAT CE 2020 the default.

**Comment by senier** [comment] 2020-05-28 16:31
Yes

**Comment by jklmnn** [comment] 2020-05-28 17:15
Okay the problem is not only when proving but also that the version that GNAT CE 2020 is able to prove does not compile on any older compiler.

**Comment by jklmnn** [comment] 2020-06-03 10:53
Closed by #179.

**Closed by jklmnn** 2020-06-03 10:53 UTC
